substitutions:
  _REGION: us-central1
  _SERVICE: atf-frontend

steps:
  # 1️⃣ Build imagen Docker (con variables Vite)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA
      - --build-arg
      - VITE_AUTH0_DOMAIN=${_VITE_AUTH0_DOMAIN}
      - --build-arg
      - VITE_AUTH0_CLIENT_ID=${_VITE_AUTH0_CLIENT_ID}
      - --build-arg
      - VITE_AUTH0_AUDIENCE=${_VITE_AUTH0_AUDIENCE}
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - --build-arg
      - VITE_MAPBOX_TOKEN=${_VITE_MAPBOX_TOKEN}
      - .

  # 2️⃣ Push a Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA

  # 3️⃣ Deploy a Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "80"

images:
  - gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
